spring:
    application:
        name: Hexagonal Namecard
    messages:
        encoding: UTF-8
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                web-allow-others: true
    datasource:
        driver-class-name: org.h2.Driver
        url: "jdbc:h2:mem:spring_assignments;MODE=MYSQL;"
        username: sa
        password:
        hikari:
            minimum-idle: 1
            maximum-pool-size: 5
            pool-name: H2_DB
    sql:
        init:
            platform: h2
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format_sql: true
                show_sql: true
        defer-datasource-initialization: true
    redis:
        host: localhost
        port: 6379
server:
    port: 7777
jwt:
    secret: "HEXAGONAL_NAMECARD_JWT_TOKEN_SECRET_KEY_VALUE"
    access:
        #expiration: 300000 #5분 (5 * 60) * 1000
        expiration: 864000000 #10일 (60 * 60 * 24 * 10) * 1000
        header: "X-AUTH-TOKEN"
    refresh:
        expiration: 864000000 #10일 (60 * 60 * 24 * 10) * 1000
        header: "X-REFRESH-TOKEN"